version: "3"

tasks:
  dev:
    desc: Run Hugo dev server (live reload)
    cmds:
      - docker compose --profile dev up --build
  preview:
    desc: Build and run production-like container locally
    cmds:
      - docker compose --profile preview up --build
  clean:
    desc: Stop and remove containers
    cmds:
      - docker compose down -v
